name: Run Python Script Every Hour

on:
  schedule:
    - cron: '1 * * * *'  # 매 시간 1분에 실행
  push:
    branches:
      - main
  workflow_dispatch:  # 수동 실행도 가능하게

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # 필요하면 다른 버전으로 변경

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if test -f requirements.txt; then pip install -r requirements.txt; fi

      - name: Run Python script
        run: python autoweatherrecordtosupabase.py
